### ISSUE TITLE
LSE_CLOCK not working. 

### ISSUE THREAD

**Issue by arun912-ux** [stm32duino/STM32RTC#36] opened 2020-07-26 04:19 UTC
Hi.
I'm using STM32 Bluepill with 3V vb attached
I've uploaded the example Simple RTC with LSE_clock source. 
But nothing works. Clock doesn't show up.
Need help.

**Comment by fpistm** [comment] 2020-08-05 15:09
Duplicate of #33

**Closed** 2020-08-05 15:09 UTC
Labels: duplicate
