### ISSUE TITLE
LSE_CLOCK Need Help

### ISSUE THREAD

**Issue by arun912-ux** [stm32duino/STM32RTC#35] opened 2020-07-24 10:24 UTC
Hi.
I'm using Simple RTC code for time. 
I've set the Clock source to LSE_CLOCK. After unloading the code, nothing appears in Serial Monitor. 

Need help. 
Thanks in advance

**Comment by fpistm** [comment] 2020-08-05 15:09
Duplicate of #33

**Closed by fpistm** 2020-08-05 15:09 UTC
